# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

# sudo docker run -p 54321:54321 --privileged rgb

RUN apt-get update
RUN apt-get install -y build-essential

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip3 install "Pillow==8.2.0"

# Cloned from https://github.com/hzeller/rpi-rgb-led-matrix.git
COPY rpi-rgb-led-matrix rpi-rgb-led-matrix
WORKDIR /app/rpi-rgb-led-matrix
RUN make build-python PYTHON=$(which python3) 
RUN make install-python PYTHON=$(which python3) 

WORKDIR /app
COPY . .



# invoke docker with -p 54321:54321 to prevent multiple concurrent runs.
EXPOSE 54321


# CMD [ "python3", "-m", "flask", "run", "--host=0.0.0.0" ]
CMD [ "python3", "rpi-rgb-led-matrix/bindings/python/samples/pulsing-colors.py", "--led-chain=2", "--led-slowdown-gpio=2" ]